// Package dotenv is a minimal KEY=VALUE reader for the product .env file.
//
// It intentionally does not implement the full dotenv spec (no variable
// expansion, no export keyword, no multi-line values) because the on-prem
// .env is generated by setup.sh and stays simple.
package dotenv

import (
	"bufio"
	"net/url"
	"os"
	"strings"
)

// Read parses path and returns the KEY=VALUE pairs. Lines that are blank
// or start with '#' are skipped. Surrounding single or double quotes are
// stripped from the value. A missing file is not an error: an empty map
// is returned.
func Read(path string) (map[string]string, error) {
	out := map[string]string{}

	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return out, nil
		}
		return nil, err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 64*1024), 1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq <= 0 {
			continue
		}
		key := strings.TrimSpace(line[:eq])
		val := strings.TrimSpace(line[eq+1:])
		val = strings.TrimSuffix(strings.TrimPrefix(val, `"`), `"`)
		val = strings.TrimSuffix(strings.TrimPrefix(val, `'`), `'`)
		out[key] = val
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// MongoURIFromEnv builds a mongodb:// URI from the MONGODB_* keys present
// in env. Returns ("", "") if MONGODB_HOST or MONGODB_PORT is missing.
// The second return value is the database name (MONGODB_DATABASE or
// MONGODB_DB), which may be empty if the caller wants to apply its own
// default.
func MongoURIFromEnv(env map[string]string) (uri, db string) {
	host := env["MONGODB_HOST"]
	port := env["MONGODB_PORT"]
	if host == "" || port == "" {
		return "", ""
	}

	user := env["MONGODB_USER"]
	pass := env["MONGODB_PASS"]

	var userinfo string
	if user != "" {
		if pass != "" {
			userinfo = url.QueryEscape(user) + ":" + url.QueryEscape(pass) + "@"
		} else {
			userinfo = url.QueryEscape(user) + "@"
		}
	}

	uri = "mongodb://" + userinfo + host + ":" + port + "/?authSource=admin"

	db = env["MONGODB_DATABASE"]
	if db == "" {
		db = env["MONGODB_DB"]
	}
	return uri, db
}
